services:

  frontend:
    container_name: frontend_1
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 8020:8020
    volumes:
      - /app
      - /app/node_modules
    networks:
      - constructionAutomation
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  
networks:
  constructionAutomation:
    external: true