services:

  frontend:
    container_name: frontend_1
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 80:80
    volumes:
      - /app
      - /app/node_modules
    networks:
      - constructionAutomation
    
  
networks:
  constructionAutomation:
    external: true