services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 8080:80
    volumes:
      - /app
      - /app/node_modules
    networks:
      - constructionAutomation
  
networks:
  constructionAutomation:
    external: true