services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 8020:8020
    volumes:
      - /app
      - /app/node_modules
    environment:
      - API_URL=http://backend:5000
    networks:
      - constructionAutomation
    
  
networks:
  constructionAutomation:
    external: true