# Stage 1: Build Angular application
FROM node:20.12-alpine3.18 as build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package.json package-lock.json ./
RUN npm install

# Устанавливаем Angular CLI
RUN npm install -g @angular/cli

# Копируем остальные файлы проекта и собираем приложение
COPY . .
RUN ng build --configuration production --output-path=dist

# Stage 2: Run the app using nginx
FROM nginx:stable-alpine

# Копируем скомпилированные файлы Angular в nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем файл конфигурации nginx (опционально)
COPY nginx.conf /etc/nginx/nginx.conf

# Устанавливаем переменные окружения
ENV TZ=Europe/Zurich

# Открываем порт 80
EXPOSE 80

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]
